import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))

from nlq_engine import (
    fetch_results_for_nl_query,
    generate_dsl_for_query,
    run_dsl_against_es,
    ES_INDEX
)
import json
from typing import Dict, Any, List, Optional, Tuple
from ..core.config import settings
import logging

logger = logging.getLogger(__name__)

def build_dsl_from_intent(query: str) -> Dict[str, Any]:
    """
    Revolutionary AI-first NLQ engine that uses LLM to generate complete Elasticsearch DSL.
    NO local regex/keyword matching - the LLM must produce the entire ES query DSL.
    
    This completely replaces the previous intent-based approach with pure LLM-driven DSL generation.
    """
    try:
        logger.info(f"Processing NLQ query with LLM: '{query}'")
        
        # Use the new LLM-first engine to generate complete DSL
        parsed_json, raw_output = generate_dsl_for_query(
            nl_query=query,
            index_name=ES_INDEX,
            debug=True
        )
        
        # Return the structured response expected by the backend
        return {
            "query_intent": parsed_json.get("intent", "unknown"),
            "confidence_score": parsed_json.get("confidence", 0.0),
            "explanation": parsed_json.get("explain", ""),
            "es_dsl": parsed_json["es_dsl"],
            "raw_llm_output": raw_output[:500] + "..." if len(raw_output) > 500 else raw_output,
            "original_query": query,
            "llm_generated": True,  # Flag to indicate this came from LLM
            "processing_method": "llm_first"
        }
        
    except Exception as e:
        logger.error(f"LLM-first DSL generation failed: {e}")
        
        # Fail loudly as specified - do NOT fall back to keyword matching
        return {
            "query_intent": "error",
            "confidence_score": 0.0,
            "explanation": f"LLM DSL generation failed: {str(e)}",
            "es_dsl": {},  # Empty DSL to indicate failure
            "raw_llm_output": str(e),
            "original_query": query,
            "llm_generated": False,
            "processing_method": "failed",
            "error": str(e)
        }

def to_es_query(plan: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract and return the Elasticsearch DSL generated by the LLM.
    
    This function now simply returns the DSL produced by the LLM without modification,
    maintaining the principle that the LLM generates the complete query structure.
    """
    
    if plan.get("llm_generated", False):
        # LLM successfully generated DSL - return it exactly as provided
        es_dsl = plan.get("es_dsl", {})
        
        if not es_dsl:
            logger.warning("LLM generated empty DSL")
            # Return a minimal fallback that will return no results
            return {
                "query": {"match_none": {}},
                "size": 0
            }
        
        logger.info(f"Returning LLM-generated DSL: {json.dumps(es_dsl, indent=2)[:300]}...")
        return es_dsl
    
    else:
        # LLM failed - return error query that explains the failure
        error_msg = plan.get("error", "Unknown error in LLM processing")
        logger.error(f"Cannot generate ES query - LLM failed: {error_msg}")
        
        return {
            "query": {"match_none": {}},
            "size": 0,
            "_comment": f"LLM DSL generation failed: {error_msg}"
        }

def execute_full_nlq_pipeline(query: str, debug: bool = True) -> Dict[str, Any]:
    """
    Execute the complete NLQ pipeline from natural language to results.
    
    This is the main entry point that performs:
    1. LLM-based DSL generation
    2. Elasticsearch execution  
    3. Result processing and logging
    
    Returns complete results including LLM analysis and ES response.
    """
    try:
        logger.info(f"Executing full NLQ pipeline for: '{query}'")
        
        # Use the complete NLQ engine pipeline
        result = fetch_results_for_nl_query(
            nl_query=query,
            index_name=ES_INDEX,
            debug=debug
        )
        
        # Add backend-specific metadata
        result["backend_processing"] = {
            "timestamp": result.get("es_result", {}).get("took", 0),
            "total_hits": result.get("es_result", {}).get("hits", {}).get("total", {}).get("value", 0),
            "max_score": result.get("es_result", {}).get("hits", {}).get("max_score", 0.0),
            "processing_method": "llm_first_complete"
        }
        
        logger.info(f"NLQ pipeline completed successfully - found {result['backend_processing']['total_hits']} results")
        return result
        
    except Exception as e:
        logger.error(f"Full NLQ pipeline failed: {e}")
        return {
            "nl_query": query,
            "error": str(e),
            "backend_processing": {
                "processing_method": "failed",
                "error_details": str(e)
            }
        }

# Legacy function stubs for backward compatibility
def _model():
    """Legacy model function - now handled by nlq_engine"""
    logger.warning("Legacy _model() function called - should use nlq_engine instead")
    return None

def _analyze_forensic_intent(query: str) -> Dict[str, Any]:
    """Legacy intent analysis - now handled by LLM in nlq_engine"""
    logger.warning("Legacy intent analysis called - should use nlq_engine instead")
    return {"primary_intent": "unknown", "confidence": 0.0}

# Maintain helper functions for any existing dependencies
def _extract_json_from_response(response_text: str) -> str:
    """Extract JSON from AI response, handling various formats"""
    if "```json" in response_text:
        try:
            return response_text.split("```json")[1].split("```")[0].strip()
        except:
            pass
    elif "```" in response_text:
        try:
            return response_text.split("```")[1].strip()
        except:
            pass
    
    # Try to find JSON object in response
    start = response_text.find("{")
    end = response_text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return response_text[start:end + 1]
    
    return response_text.strip()