import os
import tempfile
from datetime import datetime
from typing import Dict, Any
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER


def generate_report(api_response: Dict[str, Any]) -> str:
    temp_dir = tempfile.mkdtemp(prefix="forensic_report_")

    results = api_response.get("results", [])
    case_id = "unknown"
    if results and results[0].get("case_id"):
        case_id = results[0]["case_id"]

    pdf_filename = f"forensic_report_{case_id}.pdf"
    pdf_path = os.path.join(temp_dir, pdf_filename)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=18,
        leftMargin=18,
        topMargin=18,
        bottomMargin=18,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=8,
        alignment=TA_CENTER,
        textColor=colors.black,
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=12,
        spaceAfter=6,
        spaceBefore=8,
        textColor=colors.black,
    )

    centered_style = ParagraphStyle(
        "CenteredNormal",
        parent=styles["Normal"],
        fontSize=10,
        alignment=TA_CENTER,
        textColor=colors.black,
    )

    message_style = ParagraphStyle(
        "MessageStyle",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.black,
        leftIndent=0,
        rightIndent=0,
        wordWrap="CJK",
    )

    story = []

    story.append(Paragraph("Digital Forensic Report", title_style))
    story.append(Paragraph("Generated by cognito.ai", centered_style))
    story.append(Spacer(1, 8))

    results = api_response.get("results", [])

    story.append(Paragraph("Report Information", heading_style))

    report_data = [["Field", "Value"]]

    report_data.append(
        ["Report Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
    )
    if api_response.get("query"):
        report_data.append(["Search Query:", api_response["query"]])
    if api_response.get("query_intent"):
        report_data.append(["Query Intent:", api_response["query_intent"]])
    if api_response.get("total_results") is not None:
        report_data.append(["Total Results:", str(api_response["total_results"])])

    report_table = Table(report_data, colWidths=[2 * inch, 4 * inch])
    report_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ]
        )
    )

    story.append(report_table)
    story.append(Spacer(1, 8))

    if results:
        first_result = results[0]

        story.append(Paragraph("Chain of Custody", heading_style))

        custody_data = [["Field", "Value"]]

        if first_result.get("artifact_id"):
            custody_data.append(["Artifact ID", first_result["artifact_id"]])
        if first_result.get("case_id"):
            custody_data.append(["Case ID", first_result["case_id"]])
        if first_result.get("device_id"):
            custody_data.append(["Device ID", first_result["device_id"]])

        custody_data.extend(
            [["Investigating Officer", "Not Provided"], ["Officer ID", "Not Provided"]]
        )

    custody_table = Table(custody_data, colWidths=[2 * inch, 4 * inch])
    custody_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ]
        )
    )

    story.append(custody_table)
    story.append(Spacer(1, 8))

    story.append(Paragraph("Items Submitted", heading_style))

    source_paths = set()
    for result in results:
        source_path = result.get("source_path", "")
        if source_path:
            source_paths.add(source_path)

    if source_paths:
        items_data = [["Item", "Source Path"]]
        for i, path in enumerate(source_paths, 1):
            items_data.append([f"{i}.", Paragraph(path, styles["Normal"])])
    else:
        items_data = [["Item", "Source Path"], ["1.", "No source paths available"]]

    items_table = Table(items_data, colWidths=[0.5 * inch, 5.5 * inch])
    items_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
            ]
        )
    )

    story.append(items_table)
    story.append(Spacer(1, 8))

    story.append(Paragraph("Examination Results", heading_style))

    if results:
        headers = []
        field_mappings = {
            "sending_party": "Sender",
            "conversation_name": "Conversation",
            "timestamp": "Timestamp",
            "message_timestamp": "Timestamp",
            "message": "Message",
            "sender": "Sender",
            "from": "From",
            "to": "To",
            "subject": "Subject",
            "body": "Body",
            "content": "Content",
            "url": "URL",
            "filename": "Filename",
            "file_path": "File Path",
        }

        for field, display_name in field_mappings.items():
            if any(result.get(field) for result in results):
                if display_name not in headers:
                    headers.append(display_name)

        if not headers:
            headers = ["Data"]

        results_data = [headers]

        for result in results:
            row = []
            for field, display_name in field_mappings.items():
                if display_name in headers and result.get(field):
                    value = result.get(field)
                    row.append(Paragraph(str(value), message_style))

            if not row:
                row = [str(result.get("data", "No data"))]

            results_data.append(row)

        if len(headers) == 4:
            col_widths = [0.8 * inch, 0.8 * inch, 1.4 * inch, 3 * inch]
        elif len(headers) == 3:
            col_widths = [1 * inch, 1 * inch, 4 * inch]
        elif len(headers) == 2:
            col_widths = [1.5 * inch, 4.5 * inch]
        else:
            col_widths = [6 * inch / len(headers)] * len(headers)

        results_table = Table(results_data, colWidths=col_widths)
        results_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("GRID", (0, 0), (-1, -1), 1, colors.black),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
                ]
            )
        )

        story.append(results_table)
    else:
        story.append(Paragraph("No examination results found.", styles["Normal"]))

    doc.build(story)

    return pdf_path
