import os
import tempfile
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_report(api_response: Dict[str, Any]) -> str:
    temp_dir = tempfile.mkdtemp(prefix="pdf_")
    results = api_response.get("results", [])
    case_id = api_response.get("case_id", "unknown")
    pdf_path = os.path.join(temp_dir, f"{case_id}.pdf")

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=12,
        textColor=colors.HexColor("#2c3e50"),
        fontName="Helvetica-Bold",
    )
    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=12,
        spaceAfter=8,
        textColor=colors.HexColor("#34495e"),
        fontName="Helvetica-Bold",
    )
    centered_style = ParagraphStyle(
        "CenteredNormal",
        parent=styles["Normal"],
        fontSize=11,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#7f8c8d"),
    )
    message_style = ParagraphStyle(
        "Message",
        parent=styles["Normal"],
        fontSize=9,
        wordWrap="CJK",
        leading=12,
        textColor=colors.HexColor("#2c3e50"),
    )

    sections = api_response.get("sections", {}) or {}
    include_report_info = sections.get("report_information", True)
    include_chain = sections.get("chain_of_custody", True)
    include_sources = sections.get("evidence_sources", True)
    include_executive = sections.get("executive_summary", True)
    include_detailed = sections.get("detailed_examination_results", False)

    story = [
        Paragraph("Digital Forensic Report", title_style),
        Paragraph("Generated by cognito.ai", centered_style),
        Spacer(1, 16),
    ]

    if include_report_info:
        story.append(Paragraph("Report Information", heading_style))

    report_data = [["Field", "Value"]]
    report_data.append(
        ["Report Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
    )

    if api_response.get("query"):
        report_data.append(["Search Query", api_response["query"]])
    if api_response.get("intent"):
        report_data.append(["Query Intent", api_response["intent"]])
    if api_response.get("totalResults") is not None:
        report_data.append(["Total Results", str(api_response["totalResults"])])

        story.append(build_table(report_data, [2 * inch, 5.5 * inch]))

    if results and include_chain:
        first_result = results[0]
        story.append(Spacer(1, 12))
        story.append(Paragraph("Chain of Custody", heading_style))

        custody_data = [["Field", "Value"]]

        if first_result.get("case_id"):
            custody_data.append(["Case ID", first_result["case_id"]])
        if first_result.get("device_id"):
            custody_data.append(["Device ID", first_result["device_id"]])

        custody_data.append(["Evidence Type", "Digital Communications"])
        custody_data.append(["Collection Method", "Automated Extraction"])
        custody_data.append(["Collection Date", datetime.now().strftime("%Y-%m-%d")])
        custody_data.append(["Collection Time", datetime.now().strftime("%H:%M:%S")])
        custody_data.append(["Analysis Tool", "Cognito AI Forensic Platform"])
        custody_data.append(["Analysis Date", datetime.now().strftime("%Y-%m-%d")])
        custody_data.append(["Total Artifacts", str(len(results))])

        custody_data.extend(
            [
                ["Investigating Officer", "_________________"],
                ["Officer ID", "_________________"],
                ["Supervisor", "_________________"],
                ["Lab Technician", "_________________"],
            ]
        )

        story.append(build_table(custody_data, [2.5 * inch, 4.5 * inch]))

    if include_sources:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Evidence Sources", heading_style))

        source_files = {}
        for res in results:
            source_path = res.get("source", "")
            if source_path:
                filename = (
                    source_path.split("\\")[-1]
                    if "\\" in source_path
                    else source_path.split("/")[-1]
                )
                app = res.get("app", "Unknown")
                file_type = res.get("file_type", "Unknown")

                if filename not in source_files:
                    source_files[filename] = {
                        "app": app,
                        "file_type": file_type,
                        "count": 1,
                        "full_path": source_path,
                    }
                else:
                    source_files[filename]["count"] += 1

        styles = getSampleStyleSheet()
        header_style = ParagraphStyle(
            "EvidenceHeader",
            parent=styles["Normal"],
            fontSize=10,
            fontName="Helvetica-Bold",
        )

        evidence_data = [
            [
                Paragraph("Evidence File", header_style),
                Paragraph("Application", header_style),
                Paragraph("Data Type", header_style),
                Paragraph("Records", header_style),
                Paragraph("Source Path", header_style),
            ]
        ]

        for i, (filename, info) in enumerate(list(source_files.items())[:8], 1):
            normal_style = ParagraphStyle(
                "EvidenceNormal", parent=styles["Normal"], fontSize=9, wordWrap="CJK"
            )
            evidence_data.append(
                [
                    Paragraph(f"{i}. {filename}", normal_style),
                    Paragraph(info["app"], normal_style),
                    Paragraph(info["file_type"], normal_style),
                    Paragraph(str(info["count"]), normal_style),
                    Paragraph(info["full_path"], normal_style),
                ]
            )

        if len(source_files) > 8:
            remaining_count = sum(
                info["count"] for info in list(source_files.values())[8:]
            )
            evidence_data.append(
                [
                    Paragraph(
                        f"... and {len(source_files) - 8} more files", normal_style
                    ),
                    Paragraph("", normal_style),
                    Paragraph("", normal_style),
                    Paragraph(str(remaining_count), normal_style),
                    Paragraph("", normal_style),
                ]
            )

        story.append(
            build_table(
                evidence_data,
                [1.0 * inch, 2.2 * inch, 2.2 * inch, 0.6 * inch, 1.5 * inch],
            )
        )

    if include_executive:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Executive Summary", heading_style))

        total_messages = len(results)
        apps_summary = {}
        directions_summary = {"Incoming": 0, "Outgoing": 0}

        for res in results:
            app = res.get("app", "Unknown")
            apps_summary[app] = apps_summary.get(app, 0) + 1
            direction = res.get("direction", "Unknown")
            if direction in directions_summary:
                directions_summary[direction] += 1

        summary_data = [["Metric", "Value"]]
        summary_data.append(["Total Communications Analyzed", str(total_messages)])
        summary_data.append(["Applications Involved", str(len(apps_summary))])
        summary_data.append(["Incoming Messages", str(directions_summary["Incoming"])])
        summary_data.append(["Outgoing Messages", str(directions_summary["Outgoing"])])
        summary_data.append(
            [
                "Primary Application",
                max(apps_summary.items(), key=lambda x: x[1])[0]
                if apps_summary
                else "N/A",
            ]
        )

        story.append(build_table(summary_data, [2.5 * inch, 4.5 * inch]))

    if include_detailed:
        story.append(Spacer(1, 12))
        story.append(Paragraph("Detailed Examination Results", heading_style))

        if results:
            max_results = 50
            if len(results) > max_results:
                story.append(
                    Paragraph(
                        f"Showing first {max_results} of {len(results)} results:",
                        styles["Normal"],
                    )
                )
                results_to_show = results[:max_results]
            else:
                results_to_show = results

            story.append(build_results(results_to_show, message_style))

            if len(results) > max_results:
                story.append(Spacer(1, 12))
                story.append(
                    Paragraph(
                        f"Note: {len(results) - max_results} additional results not shown in this report.",
                        styles["Normal"],
                    )
                )
        else:
            story.append(Paragraph("No examination results found.", styles["Normal"]))

    doc.build(story)
    return pdf_path


def build_table(data: List[List[Any]], col_widths: List[float]) -> Table:
    table = Table(data, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#ecf0f1")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#2c3e50")),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("FONTSIZE", (0, 1), (-1, -1), 9),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#bdc3c7")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#f8f9fa")],
                ),
            ]
        )
    )
    return table


def build_results(results: List[Dict[str, Any]], style: ParagraphStyle) -> Table:
    field_map = {
        "artifact_id": "Artifact ID",
        "timestamp": "Timestamp",
        "sender": "Sender",
        "content": "Content",
        "app": "App",
        "direction": "Direction",
        "conversation_name": "Conversation",
        "source": "Source File",
        "status": "Status",
    }

    headers = []
    header_fields = []
    for field, name in field_map.items():
        if any(res.get(field) and str(res.get(field)).strip() for res in results):
            headers.append(name)
            header_fields.append(field)

    if not headers:
        headers = ["Content"]
        header_fields = ["content"]

    header_style = ParagraphStyle(
        "ResultsHeader",
        parent=getSampleStyleSheet()["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
    )

    results_data = [[Paragraph(header, header_style) for header in headers]]

    for res in results:
        row = []
        for field in header_fields:
            value = res.get(field, "")
            if value and str(value).strip():
                if field == "content":
                    content = str(value).strip().replace("\n", "<br/>")
                    row.append(Paragraph(content, style))
                elif field == "source":
                    row.append(Paragraph(str(value).strip(), style))
                elif field == "timestamp":
                    row.append(Paragraph(str(value), style))
                elif field == "artifact_id":
                    row.append(Paragraph(str(value), style))
                else:
                    row.append(Paragraph(str(value).strip(), style))
            else:
                row.append(Paragraph("", style))

        if not row:
            content = res.get("content", "No data")
            row = [Paragraph(content.replace("\n", "<br/>"), style)]

        results_data.append(row)

    num_cols = len(headers)
    if num_cols == 1:
        col_widths = [7.5 * inch]
    elif num_cols == 2:
        col_widths = [2 * inch, 5.5 * inch]
    elif num_cols == 3:
        col_widths = [1.5 * inch, 1.5 * inch, 4.5 * inch]
    elif num_cols == 4:
        col_widths = [1.2 * inch, 1.2 * inch, 1.2 * inch, 3.9 * inch]
    elif num_cols == 5:
        col_widths = [1 * inch, 1 * inch, 1 * inch, 1 * inch, 3.5 * inch]
    else:
        col_widths = [min(1.2 * inch, 7.5 * inch / num_cols)] * num_cols

    table = Table(results_data, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#f9f9f9")],
                ),
            ]
        )
    )
    return table
