import os
import tempfile
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_report(api_response: Dict[str, Any]) -> str:
    temp_dir = tempfile.mkdtemp(prefix="pdf_")
    results = api_response.get("results", [])
    case_id = api_response.get("case_id", "unknown")
    pdf_path = os.path.join(temp_dir, f"{case_id}.pdf")

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=18,
        leftMargin=18,
        topMargin=18,
        bottomMargin=18,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=16,
        alignment=TA_CENTER,
        spaceAfter=8,
        textColor=colors.black,
    )
    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        fontSize=12,
        spaceBefore=8,
        spaceAfter=6,
        textColor=colors.black,
    )
    centered_style = ParagraphStyle(
        "CenteredNormal", parent=styles["Normal"], fontSize=10, alignment=TA_CENTER
    )
    message_style = ParagraphStyle(
        "Message", parent=styles["Normal"], fontSize=8, wordWrap="CJK"
    )

    story = [
        Paragraph("Digital Forensic Report", title_style),
        Paragraph("Generated by cognito.ai", centered_style),
        Spacer(1, 8),
        Paragraph("Report Information", heading_style),
    ]

    report_data = [["Field", "Value"]]
    report_data.append(
        ["Report Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
    )
    if api_response.get("query"):
        report_data.append(["Search Query:", api_response["query"]])
    if api_response.get("query_intent"):
        report_data.append(["Query Intent:", api_response["query_intent"]])
    if api_response.get("total_results") is not None:
        report_data.append(["Total Results:", str(api_response["total_results"])])

    story.append(build_table(report_data, [2 * inch, 4 * inch]))

    if results:
        first_result = results[0]
        story.append(Spacer(1, 8))
        story.append(Paragraph("Chain of Custody", heading_style))
        custody_data = [["Field", "Value"]]
        for field in ["artifact_id", "case_id", "device_id"]:
            if first_result.get(field):
                custody_data.append(
                    [field.replace("_", " ").title(), first_result[field]]
                )
        custody_data.extend(
            [["Investigating Officer", "Not Provided"], ["Officer ID", "Not Provided"]]
        )
        story.append(build_table(custody_data, [2 * inch, 4 * inch]))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Items Submitted", heading_style))
    source_paths = list(
        {res.get("source_path", "") for res in results if res.get("source_path")}
    )
    if not source_paths:
        source_paths = ["No source paths available"]
    items_data = [["Item", "Source Path"]]
    for i, path in enumerate(source_paths, 1):
        items_data.append([f"{i}.", Paragraph(path, styles["Normal"]) if path else ""])
    story.append(build_table(items_data, [0.5 * inch, 5.5 * inch]))

    story.append(Spacer(1, 8))
    story.append(Paragraph("Examination Results", heading_style))
    if results:
        story.append(build_results(results, message_style))
    else:
        story.append(Paragraph("No examination results found.", styles["Normal"]))

    doc.build(story)
    return pdf_path


def build_table(data: List[List[Any]], col_widths: List[float]) -> Table:
    table = Table(data, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
            ]
        )
    )
    return table


def build_results(results: List[Dict[str, Any]], style: ParagraphStyle) -> Table:
    field_map = {
        "sending_party": "Sender",
        "conversation_name": "Conversation",
        "timestamp": "Timestamp",
        "message_timestamp": "Timestamp",
        "message": "Message",
        "sender": "Sender",
        "from": "From",
        "to": "To",
        "subject": "Subject",
        "body": "Body",
        "content": "Content",
        "url": "URL",
        "filename": "Filename",
        "file_path": "File Path",
    }

    headers = [
        name
        for field, name in field_map.items()
        if any(res.get(field) for res in results)
    ]
    if not headers:
        headers = ["Data"]

    results_data = [headers]
    for res in results:
        row = [
            Paragraph(str(res.get(f, "")), style)
            for f, name in field_map.items()
            if name in headers
        ]
        if not row:
            row = [str(res.get("data", "No data"))]
        results_data.append(row)

    col_width_map = {2: [1.5, 4.5], 3: [1, 1, 4], 4: [0.8, 0.8, 1.4, 3]}
    col_widths = col_width_map.get(
        len(headers), [6 * inch / len(headers)] * len(headers)
    )

    table = Table(results_data, colWidths=col_widths)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("WORDWRAP", (0, 0), (-1, -1), "CJK"),
            ]
        )
    )
    return table
